from datetime import timezone, timedelta

TYPE_INCOME = 1
TYPE_OUTCOME = 2
TYPE_SAVING = 3

# account type
ACCOUNT_CASH = 1
ACCOUNT_CARD = 2
ACCOUNT_OTHER = 3

# asset type
ASSET_BANK = 1
ASSET_INSTALLMENT_SAVING = 2
ASSET_STOCK = 3
ASSET_PROPERTY = 4
ASSET_CAR = 5
ASSET_ANNUITY = 6
ASSET_ETC = 7

CURRENT_TIMEZONE = timezone(timedelta(hours=9))


__all__ = [
    "TYPE_INCOME",
    "TYPE_OUTCOME",
    "TYPE_SAVING",
    "ACCOUNT_CASH",
    "ACCOUNT_CARD",
    "ACCOUNT_OTHER",
    "ASSET_BANK",
    "ASSET_INSTALLMENT_SAVING",
    "ASSET_STOCK",
    "ASSET_PROPERTY",
    "ASSET_CAR",
    "ASSET_ANNUITY",
    "ASSET_ETC",
    "CURRENT_TIMEZONE",
]
