"""empty message

Revision ID: 662a01341658
Revises: cc0188d43c1b
Create Date: 2023-05-13 20:25:15.848221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "662a01341658"
down_revision = "cc0188d43c1b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("loans", sa.Column("payment_amount", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("loans", "payment_amount")
    # ### end Alembic commands ###
