"""empty message

Revision ID: cc0188d43c1b
Revises: 89a8ed64fc1c
Create Date: 2023-05-08 14:47:06.257722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cc0188d43c1b"
down_revision = "89a8ed64fc1c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("loans", sa.Column("amount", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("loans", "amount")
    # ### end Alembic commands ###
