"""empty message

Revision ID: ef7ddecbb86f
Revises: aaa943c456a8
Create Date: 2023-05-06 12:42:04.067112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ef7ddecbb86f"
down_revision = "aaa943c456a8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
