"""empty message

Revision ID: fd280dbb8b78
Revises: d0f374378b03
Create Date: 2023-05-25 13:56:32.001852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fd280dbb8b78"
down_revision = "d0f374378b03"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_cards_version",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("name", sa.String(length=50), autoincrement=False, nullable=True),
        sa.Column("card_type", sa.Integer(), autoincrement=False, nullable=True),
        sa.Column("amount", sa.Integer(), autoincrement=False, nullable=True),
        sa.Column("description", sa.Text(), autoincrement=False, nullable=True),
        sa.Column("created_at", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column("updated_at", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column(
            "transaction_id", sa.BigInteger(), autoincrement=False, nullable=False
        ),
        sa.Column("end_transaction_id", sa.BigInteger(), nullable=True),
        sa.Column("operation_type", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", "transaction_id"),
    )
    op.create_index(
        op.f("ix_account_cards_version_end_transaction_id"),
        "account_cards_version",
        ["end_transaction_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_account_cards_version_id"),
        "account_cards_version",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_account_cards_version_operation_type"),
        "account_cards_version",
        ["operation_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_account_cards_version_transaction_id"),
        "account_cards_version",
        ["transaction_id"],
        unique=False,
    )
    op.create_table(
        "assets_version",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("name", sa.String(length=50), autoincrement=False, nullable=True),
        sa.Column("asset_type", sa.Integer(), autoincrement=False, nullable=True),
        sa.Column("amount", sa.Integer(), autoincrement=False, nullable=True),
        sa.Column("description", sa.Text(), autoincrement=False, nullable=True),
        sa.Column("created_at", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column("updated_at", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column(
            "transaction_id", sa.BigInteger(), autoincrement=False, nullable=False
        ),
        sa.Column("end_transaction_id", sa.BigInteger(), nullable=True),
        sa.Column("operation_type", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", "transaction_id"),
    )
    op.create_index(
        op.f("ix_assets_version_end_transaction_id"),
        "assets_version",
        ["end_transaction_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assets_version_id"), "assets_version", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_assets_version_operation_type"),
        "assets_version",
        ["operation_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assets_version_transaction_id"),
        "assets_version",
        ["transaction_id"],
        unique=False,
    )
    op.create_table(
        "categories_version",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("name", sa.String(length=50), autoincrement=False, nullable=True),
        sa.Column("main_category_id", sa.Integer(), autoincrement=False, nullable=True),
        sa.Column("created_at", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column("updated_at", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column(
            "transaction_id", sa.BigInteger(), autoincrement=False, nullable=False
        ),
        sa.Column("end_transaction_id", sa.BigInteger(), nullable=True),
        sa.Column("operation_type", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", "transaction_id"),
    )
    op.create_index(
        op.f("ix_categories_version_end_transaction_id"),
        "categories_version",
        ["end_transaction_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_categories_version_id"), "categories_version", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_categories_version_operation_type"),
        "categories_version",
        ["operation_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_categories_version_transaction_id"),
        "categories_version",
        ["transaction_id"],
        unique=False,
    )
    op.create_table(
        "loans_version",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("name", sa.String(length=50), autoincrement=False, nullable=True),
        sa.Column("principal", sa.Integer(), autoincrement=False, nullable=True),
        sa.Column("interest_rate", sa.Float(), autoincrement=False, nullable=True),
        sa.Column("total_months", sa.Integer(), autoincrement=False, nullable=True),
        sa.Column("payment_amount", sa.Integer(), autoincrement=False, nullable=True),
        sa.Column("current_month", sa.Integer(), autoincrement=False, nullable=True),
        sa.Column("description", sa.Text(), autoincrement=False, nullable=True),
        sa.Column("amount", sa.Integer(), autoincrement=False, nullable=True),
        sa.Column("created_at", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column("updated_at", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column(
            "transaction_id", sa.BigInteger(), autoincrement=False, nullable=False
        ),
        sa.Column("end_transaction_id", sa.BigInteger(), nullable=True),
        sa.Column("operation_type", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", "transaction_id"),
    )
    op.create_index(
        op.f("ix_loans_version_end_transaction_id"),
        "loans_version",
        ["end_transaction_id"],
        unique=False,
    )
    op.create_index(op.f("ix_loans_version_id"), "loans_version", ["id"], unique=False)
    op.create_index(
        op.f("ix_loans_version_operation_type"),
        "loans_version",
        ["operation_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_loans_version_transaction_id"),
        "loans_version",
        ["transaction_id"],
        unique=False,
    )
    op.create_table(
        "main_categories_version",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("name", sa.String(length=50), autoincrement=False, nullable=True),
        sa.Column("weekly_limit", sa.Integer(), autoincrement=False, nullable=True),
        sa.Column("category_type", sa.Integer(), autoincrement=False, nullable=True),
        sa.Column("created_at", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column("updated_at", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column(
            "transaction_id", sa.BigInteger(), autoincrement=False, nullable=False
        ),
        sa.Column("end_transaction_id", sa.BigInteger(), nullable=True),
        sa.Column("operation_type", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", "transaction_id"),
    )
    op.create_index(
        op.f("ix_main_categories_version_end_transaction_id"),
        "main_categories_version",
        ["end_transaction_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_main_categories_version_id"),
        "main_categories_version",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_main_categories_version_name"),
        "main_categories_version",
        ["name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_main_categories_version_operation_type"),
        "main_categories_version",
        ["operation_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_main_categories_version_transaction_id"),
        "main_categories_version",
        ["transaction_id"],
        unique=False,
    )
    op.create_table(
        "statements_version",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("name", sa.String(length=255), autoincrement=False, nullable=False),
        sa.Column("category_id", sa.Integer(), autoincrement=False, nullable=True),
        sa.Column("account_card_id", sa.Integer(), autoincrement=False, nullable=True),
        sa.Column("asset_id", sa.Integer(), autoincrement=False, nullable=True),
        sa.Column("loan_id", sa.Integer(), autoincrement=False, nullable=True),
        sa.Column("amount", sa.Integer(), autoincrement=False, nullable=True),
        sa.Column("discount", sa.Integer(), autoincrement=False, nullable=True),
        sa.Column("saving", sa.Integer(), autoincrement=False, nullable=True),
        sa.Column("date", sa.DateTime(), autoincrement=False, nullable=False),
        sa.Column("is_fixed", sa.Boolean(), autoincrement=False, nullable=True),
        sa.Column("description", sa.Text(), autoincrement=False, nullable=True),
        sa.Column("created_at", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column("updated_at", sa.DateTime(), autoincrement=False, nullable=True),
        sa.Column(
            "transaction_id", sa.BigInteger(), autoincrement=False, nullable=False
        ),
        sa.Column("end_transaction_id", sa.BigInteger(), nullable=True),
        sa.Column("operation_type", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", "transaction_id"),
    )
    op.create_index(
        op.f("ix_statements_version_end_transaction_id"),
        "statements_version",
        ["end_transaction_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_statements_version_id"), "statements_version", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_statements_version_operation_type"),
        "statements_version",
        ["operation_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_statements_version_transaction_id"),
        "statements_version",
        ["transaction_id"],
        unique=False,
    )
    op.create_table(
        "transaction",
        sa.Column("issued_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("remote_addr", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transaction")
    op.drop_index(
        op.f("ix_statements_version_transaction_id"), table_name="statements_version"
    )
    op.drop_index(
        op.f("ix_statements_version_operation_type"), table_name="statements_version"
    )
    op.drop_index(op.f("ix_statements_version_id"), table_name="statements_version")
    op.drop_index(
        op.f("ix_statements_version_end_transaction_id"),
        table_name="statements_version",
    )
    op.drop_table("statements_version")
    op.drop_index(
        op.f("ix_main_categories_version_transaction_id"),
        table_name="main_categories_version",
    )
    op.drop_index(
        op.f("ix_main_categories_version_operation_type"),
        table_name="main_categories_version",
    )
    op.drop_index(
        op.f("ix_main_categories_version_name"), table_name="main_categories_version"
    )
    op.drop_index(
        op.f("ix_main_categories_version_id"), table_name="main_categories_version"
    )
    op.drop_index(
        op.f("ix_main_categories_version_end_transaction_id"),
        table_name="main_categories_version",
    )
    op.drop_table("main_categories_version")
    op.drop_index(op.f("ix_loans_version_transaction_id"), table_name="loans_version")
    op.drop_index(op.f("ix_loans_version_operation_type"), table_name="loans_version")
    op.drop_index(op.f("ix_loans_version_id"), table_name="loans_version")
    op.drop_index(
        op.f("ix_loans_version_end_transaction_id"), table_name="loans_version"
    )
    op.drop_table("loans_version")
    op.drop_index(
        op.f("ix_categories_version_transaction_id"), table_name="categories_version"
    )
    op.drop_index(
        op.f("ix_categories_version_operation_type"), table_name="categories_version"
    )
    op.drop_index(op.f("ix_categories_version_id"), table_name="categories_version")
    op.drop_index(
        op.f("ix_categories_version_end_transaction_id"),
        table_name="categories_version",
    )
    op.drop_table("categories_version")
    op.drop_index(op.f("ix_assets_version_transaction_id"), table_name="assets_version")
    op.drop_index(op.f("ix_assets_version_operation_type"), table_name="assets_version")
    op.drop_index(op.f("ix_assets_version_id"), table_name="assets_version")
    op.drop_index(
        op.f("ix_assets_version_end_transaction_id"), table_name="assets_version"
    )
    op.drop_table("assets_version")
    op.drop_index(
        op.f("ix_account_cards_version_transaction_id"),
        table_name="account_cards_version",
    )
    op.drop_index(
        op.f("ix_account_cards_version_operation_type"),
        table_name="account_cards_version",
    )
    op.drop_index(
        op.f("ix_account_cards_version_id"), table_name="account_cards_version"
    )
    op.drop_index(
        op.f("ix_account_cards_version_end_transaction_id"),
        table_name="account_cards_version",
    )
    op.drop_table("account_cards_version")
    # ### end Alembic commands ###
